"""Tests for bench/parser.py against a real captured llama-bench JSON fixture.

tests/fixtures/llama_bench_smollm2.json was generated by running the pinned build:
`vendor/llama.cpp/build/bin/llama-bench -m SmolLM2-135M-Instruct-Q4_K_M.gguf -p 64 -n 32 -r 2
-o json` (docs/dev/day1-spikes.md S4 field shape).
"""

from __future__ import annotations

import pytest

from neonpilot.bench.parser import BenchParseError, parse


def test_parses_real_pp_and_tg_rows(fixture_text):
    samples = parse(fixture_text("llama_bench_smollm2.json"))

    assert len(samples) == 2
    pp, tg = samples
    assert pp.test_type == "pp"
    assert pp.n_prompt == 64
    assert pp.n_gen == 0
    assert pp.avg_ts == pytest.approx(33.705307)
    assert pp.stddev_ts == pytest.approx(22.902369)
    assert pp.samples_ts == pytest.approx([17.5109, 49.8997])

    assert tg.test_type == "tg"
    assert tg.n_gen == 32
    assert tg.avg_ts == pytest.approx(6.955916)


def test_empty_array_raises():
    with pytest.raises(BenchParseError, match="non-empty"):
        parse("[]")


def test_non_array_raises():
    with pytest.raises(BenchParseError, match="non-empty"):
        parse('{"not": "an array"}')


def test_malformed_json_raises():
    with pytest.raises(BenchParseError, match="not valid JSON"):
        parse("{not json at all")


def test_missing_required_key_raises():
    with pytest.raises(BenchParseError, match="missing required keys"):
        parse('[{"n_prompt": 64, "avg_ts": 1.0}]')


def test_non_numeric_field_raises():
    bad_row = (
        '[{"n_prompt": 64, "n_gen": 0, "avg_ts": "fast", "stddev_ts": 0.1, "samples_ts": [1.0]}]'
    )
    with pytest.raises(BenchParseError, match="non-numeric"):
        parse(bad_row)


def test_empty_samples_ts_raises():
    bad_row = '[{"n_prompt": 64, "n_gen": 0, "avg_ts": 1.0, "stddev_ts": 0.1, "samples_ts": []}]'
    with pytest.raises(BenchParseError, match="non-empty list"):
        parse(bad_row)


def test_row_with_neither_prompt_nor_gen_raises():
    bad_row = '[{"n_prompt": 0, "n_gen": 0, "avg_ts": 1.0, "stddev_ts": 0.1, "samples_ts": [1.0]}]'
    with pytest.raises(BenchParseError, match="neither n_prompt nor n_gen"):
        parse(bad_row)


def test_row_not_an_object_raises():
    with pytest.raises(BenchParseError, match="expected a JSON object"):
        parse("[42]")


@pytest.mark.parametrize("bad_value", ["NaN", "Infinity", "-Infinity"])
def test_non_finite_avg_ts_raises(bad_value):
    """M1: `json.loads` accepts NaN/Infinity/-Infinity by default (non-RFC-8259 extension) --
    a NaN/Infinity avg_ts must be rejected, not silently propagated into result.json/SVG."""
    bad_row = (
        f'[{{"n_prompt": 64, "n_gen": 0, "avg_ts": {bad_value}, '
        '"stddev_ts": 0.1, "samples_ts": [1.0]}]'
    )
    with pytest.raises(BenchParseError, match="finite, non-negative"):
        parse(bad_row)


def test_non_finite_stddev_ts_raises():
    bad_row = '[{"n_prompt": 64, "n_gen": 0, "avg_ts": 1.0, "stddev_ts": NaN, "samples_ts": [1.0]}]'
    with pytest.raises(BenchParseError, match="finite, non-negative"):
        parse(bad_row)


def test_non_finite_sample_in_samples_ts_raises():
    bad_row = (
        '[{"n_prompt": 64, "n_gen": 0, "avg_ts": 1.0, '
        '"stddev_ts": 0.1, "samples_ts": [1.0, Infinity]}]'
    )
    with pytest.raises(BenchParseError, match="finite, non-negative"):
        parse(bad_row)


def test_negative_avg_ts_raises():
    bad_row = (
        '[{"n_prompt": 64, "n_gen": 0, "avg_ts": -1.0, "stddev_ts": 0.1, "samples_ts": [1.0]}]'
    )
    with pytest.raises(BenchParseError, match="finite, non-negative"):
        parse(bad_row)
